rss_feeds:
  France24: 
    - https://www.france24.com/fr/rss
    - https://www.france24.com/fr/france/rss
  20Minutes:
    - https://www.20minutes.fr/feeds/rss-une.xml
  Le Monde:
    - https://www.lemonde.fr/rss/une.xml
  Ouest France:
    - https://www.ouest-france.fr/rss/une
  Le Monde Informatique:
    - https://www.lemondeinformatique.fr/flux-rss/thematique/internet/rss.xml
    - https://www.lemondeinformatique.fr/flux-rss/thematique/logiciel/rss.xml
    - https://www.lemondeinformatique.fr/flux-rss/thematique/securite/rss.xml
  BFM:
    - https://www.bfmtv.com/rss/news-24-7/